title: pandafy
description: "Dev Logs"
author:
  name: "pandafy"
  email: "pandafy.dev@gmail.com"
  url: "https://pandafy.me"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "pandafy"
year : "2020"
